name: "Databricks CI/CD"
on:
  push:
    branches: [ main ]
jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ github.ref == 'refs/heads/main' && 'secrets.DEV_DATABRICKS_HOST' }}
      DATABRICKS_TOKEN: ${{ github.ref == 'refs/heads/main' && 'secrets.DEV_DATABRICKS_TOKEN' }}
      DATABRICKS_CLIENT_ID: ${{ github.ref == 'refs/heads/main' && 'secrets.DEV_DATABRICKS_CLIENT_ID' }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Databricks CLI (includes built-in DAB commands)
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      # Step 3: Run structural and configuration check
      - name: Validate Asset Bundle
        run: |
          databricks bundle validate --target ${{ env.BUNDLE_TARGET }}

      # Step 4: Deploy the bundle on pushes (Merges/Commits) to main branche
      - name: Deploy Asset Bundle
        if: github.event_name == 'push'
        run: |
          databricks bundle deploy --target ${{ env.BUNDLE_TARGET }}
